CREATE TABLESPACE PDW_APEX_PDB
DATAFILE 'C:\app\PDW_APEX_PDB.dbf'
SIZE 7M
REUSE
AUTOEXTEND ON NEXT 5M
MAXSIZE 1000M
EXTENT MANAGEMENT LOCAL;
COMMIT;

CREATE TEMPORARY TABLESPACE PDW_APEX_TEMP
TEMPFILE 'C:\app\PDW_APEX_TEMP.dbf'
SIZE 5M
REUSE
AUTOEXTEND ON NEXT 3M
MAXSIZE 1000M
EXTENT MANAGEMENT LOCAL;
COMMIT;


drop tablespace PDW_APEX_PDB including contents and datafiles;
drop TABLESPACE PDW_APEX_TEMP  including contents and datafiles;

execute ADD_TEACHER('Преподаватель2');

CREATE SYNONYM "Факультет" FOR C##PDW_CORE."Факультет";
CREATE SYNONYM "Специальность" FOR C##PDW_CORE."Специальность";
CREATE SYNONYM "Дисциплина" FOR C##PDW_CORE."Дисциплина";
CREATE SYNONYM "Преподаватель" FOR C##PDW_CORE."Преподаватель";
CREATE SYNONYM "Лабораторные" FOR C##PDW_CORE."Лабораторные";
CREATE SYNONYM "Студенты" FOR C##PDW_CORE."Студенты";
CREATE SYNONYM "Подгруппы" FOR C##PDW_CORE."Подгруппы";
CREATE SYNONYM "Успеваемость" FOR C##PDW_CORE."Успеваемость";
CREATE SYNONYM "Нагрузка_преподавателя" FOR C##PDW_CORE."Нагрузка_преподавателя";
CREATE SYNONYM "Группы" FOR C##PDW_CORE."Группы";


CREATE SYNONYM ADD_DISCIPLINE FOR C##PDW_CORE.ADD_DISCIPLINE;
CREATE SYNONYM ADD_FACULTY FOR C##PDW_CORE.ADD_FACULTY;
CREATE SYNONYM ADD_GROUP FOR C##PDW_CORE.ADD_GROUP;
CREATE SYNONYM ADD_LAB FOR C##PDW_CORE.ADD_LAB;
CREATE SYNONYM ADD_SPECIALITIS FOR C##PDW_CORE.ADD_SPECIALITIS;
CREATE SYNONYM ADD_STUDENT FOR C##PDW_CORE.ADD_STUDENT;
CREATE SYNONYM ADD_SUBGROUP FOR C##PDW_CORE.ADD_SUBGROUP;
CREATE SYNONYM ADD_TEACHER FOR C##PDW_CORE.ADD_TEACHER;
CREATE SYNONYM ADD_WORK FOR C##PDW_CORE.ADD_WORK;
CREATE SYNONYM REMOVE_DISCIPLINE FOR C##PDW_CORE.REMOVE_DISCIPLINE;
CREATE SYNONYM REMOVE_FACULTY FOR C##PDW_CORE.REMOVE_FACULTY;
CREATE SYNONYM REMOVE_GROUP FOR C##PDW_CORE.REMOVE_GROUP;
CREATE SYNONYM REMOVE_LAB FOR C##PDW_CORE.REMOVE_LAB;
CREATE SYNONYM REMOVE_SPECIALITIS FOR C##PDW_CORE.REMOVE_SPECIALITIS;
CREATE SYNONYM REMOVE_STUDENT FOR C##PDW_CORE.REMOVE_STUDENT;
CREATE SYNONYM REMOVE_TEACHER FOR C##PDW_CORE.REMOVE_TEACHER;
CREATE SYNONYM REMOVE_WORK FOR C##PDW_CORE.REMOVE_WORK;
CREATE SYNONYM SET_PROGRESS FOR C##PDW_CORE.SET_PROGRESS;
CREATE SYNONYM GET_KOORS_BY_YEAR FOR C##PDW_CORE.GET_KOORS_BY_YEAR;

CREATE SYNONYM TEACHER_DISCIPLINE_LIST FOR C##PDW_CORE.TEACHER_DISCIPLINE_LIST;
CREATE SYNONYM STUDENT_LIST FOR C##PDW_CORE.STUDENT_LIST;
CREATE SYNONYM LAB_LIST FOR C##PDW_CORE.LAB_LIST;
CREATE SYNONYM KOORS_LIST FOR C##PDW_CORE.KOORS_LIST;
CREATE SYNONYM FACULTY_LIST FOR C##PDW_CORE.FACULTY_LIST;
