@procedures/ADD_DISCIPLINE.sql
@procedures/ADD_FACULTY.sql
@procedures/ADD_GROUP.sql
@procedures/ADD_LAB.sql
@procedures/ADD_SPECIALITIS.sql
@procedures/ADD_STUDENT.sql
@procedures/ADD_SUBGROUP.sql
@procedures/ADD_TEACHER.sql
@procedures/ADD_WORK.sql
@procedures/REMOVE_DISCIPLINE.sql
@procedures/REMOVE_FACULTY.sql
@procedures/REMOVE_GROUP.sql
@procedures/REMOVE_LAB.sql
@procedures/REMOVE_SPECIALITIS.sql
@procedures/REMOVE_STUDENT.sql
@procedures/REMOVE_SUBGROUP.sql
@procedures/REMOVE_TEACHER.sql
@procedures/REMOVE_WORK.sql
@procedures/SET_PROGRESS.sql
@procedures/LOAD_LABS.sql

@functions/GET_KOORS_BY_YEAR.sql