@views/TEACHER_DISCIPLINE_LIST.sql
@views/STUDENT_LIST.sql
@views/LAB_LIST.sql
@views/KOORS_LIST.sql
@views/FACULTY_LIST.sql
@views/STUDENT_DISCIPLINE.sql
@views/TEACHER_DISCIPLINE.sql
@views/LAB_DISCIPLINE.sql