DROP PUBLIC SYNONYM "Факультет" ;
DROP PUBLIC SYNONYM "Специальность";
DROP PUBLIC SYNONYM "Дисциплина" ;
DROP PUBLIC SYNONYM "Преподаватель";
DROP PUBLIC SYNONYM "Лабораторные" ;
DROP PUBLIC SYNONYM "Студенты" ;
DROP PUBLIC SYNONYM "Подгруппы" ;
DROP PUBLIC SYNONYM "Успеваемость" ;
DROP PUBLIC SYNONYM "Нагрузка_преподавателя" ;
DROP PUBLIC SYNONYM "Группы" ;


DROP PUBLIC SYNONYM ADD_DISCIPLINE;
DROP PUBLIC SYNONYM ADD_FACULTY ;
DROP PUBLIC SYNONYM ADD_GROUP ;
DROP PUBLIC SYNONYM ADD_LAB ;
DROP PUBLIC SYNONYM ADD_SPECIALITIS;
DROP PUBLIC SYNONYM ADD_STUDENT;
DROP PUBLIC SYNONYM ADD_SUBGROUP;
DROP PUBLIC SYNONYM ADD_TEACHER;
DROP PUBLIC SYNONYM ADD_WORK;
DROP PUBLIC SYNONYM REMOVE_DISCIPLINE;
DROP PUBLIC SYNONYM REMOVE_FACULTY;
DROP PUBLIC SYNONYM REMOVE_GROUP;
DROP PUBLIC SYNONYM REMOVE_LAB;
DROP PUBLIC SYNONYM REMOVE_SPECIALITIS;
DROP PUBLIC SYNONYM REMOVE_STUDENT;
DROP PUBLIC SYNONYM REMOVE_TEACHER;
DROP PUBLIC SYNONYM REMOVE_WORK;
DROP PUBLIC SYNONYM SET_PROGRESS;
DROP PUBLIC SYNONYM GET_KOORS_BY_YEAR;

DROP PUBLIC SYNONYM TEACHER_DISCIPLINE_LIST ;
DROP PUBLIC SYNONYM STUDENT_LIST;
DROP PUBLIC SYNONYM LAB_LIST;
DROP PUBLIC SYNONYM KOORS_LIST;
DROP PUBLIC SYNONYM FACULTY_LIST;
