CREATE TABLESPACE PDW_TABLESPACE
DATAFILE 'C:\app\pdw\PDW_TABLESPACE.dbf'
SIZE 7M
REUSE
AUTOEXTEND ON NEXT 5M
MAXSIZE 100M
EXTENT MANAGEMENT LOCAL;
COMMIT;

drop tablespace PDW_TABLESPACE including contents and datafiles;
drop tablespace PDW_TEMP_TABLESPACE including contents and datafiles;

CREATE TEMPORARY TABLESPACE PDW_TEMP_TABLESPACE
TEMPFILE 'C:\app\pdw\PDW_TEMP_TABLESPACE.dbf'
SIZE 5M
REUSE
AUTOEXTEND ON NEXT 3M
MAXSIZE 100M
EXTENT MANAGEMENT LOCAL;
COMMIT;

CREATE ROLE C##PDW_ROLE;

GRANT CREATE SESSION,
CREATE TABLE,
CREATE VIEW,
CREATE TRIGGER,
CREATE SEQUENCE,
CREATE PROCEDURE,
DEBUG ANY PROCEDURE, 
DEBUG CONNECT SESSION TO C##PDW_ROLE;

CREATE USER C##PDW IDENTIFIED BY 12345
DEFAULT TABLESPACE PDW_TABLESPACE 
QUOTA UNLIMITED ON PDW_TABLESPACE
TEMPORARY TABLESPACE PDW_TEMP_TABLESPACE
ACCOUNT UNLOCK;

GRANT C##PDW_ROLE TO C##PDW;
