CREATE TABLESPACE PDW_PDB
DATAFILE 'C:\app\PDW_PDB.dbf'
SIZE 7M
REUSE
AUTOEXTEND ON NEXT 5M
MAXSIZE 100M
EXTENT MANAGEMENT LOCAL;
COMMIT;

drop tablespace PDW_PDB_TEMP including contents and datafiles;
drop tablespace PDW_PDB including contents and datafiles;

CREATE TEMPORARY TABLESPACE PDW_PDB_TEMP
TEMPFILE 'C:\app\PDW_PDB_TEMP.dbf'
SIZE 5M
REUSE
AUTOEXTEND ON NEXT 3M
MAXSIZE 100M
EXTENT MANAGEMENT LOCAL;
COMMIT;

CREATE ROLE C##PDW_ROLE;

GRANT CREATE SESSION,
CREATE TABLE,
CREATE VIEW,
CREATE TRIGGER,
CREATE SEQUENCE,
CREATE PROCEDURE TO C##PDW_ROLE;

grant select
select * from "Факультет"
select * from all_tables where OWNER='C##PDW_CORE'
GRANT SELECT ON "Факультет" to APEX_050000

CREATE USER C##PDW_CORE IDENTIFIED BY 123
DEFAULT TABLESPACE PDW_PDB 
QUOTA UNLIMITED ON PDW_PDB
TEMPORARY TABLESPACE PDW_PDB_TEMP
ACCOUNT UNLOCK;

GRANT C##PDW_ROLE TO C##PDW_CORE;
