CREATE PUBLIC SYNONYM "Факультет" FOR C##PDW_CORE."Факультет";
CREATE PUBLIC SYNONYM "Специальность" FOR C##PDW_CORE."Специальность";
CREATE PUBLIC SYNONYM "Дисциплина" FOR C##PDW_CORE."Дисциплина";
CREATE PUBLIC SYNONYM "Преподаватель" FOR C##PDW_CORE."Преподаватель";
CREATE PUBLIC SYNONYM "Лабораторные" FOR C##PDW_CORE."Лабораторные";
CREATE PUBLIC SYNONYM "Студенты" FOR C##PDW_CORE."Студенты";
CREATE PUBLIC SYNONYM "Подгруппы" FOR C##PDW_CORE."Подгруппы";
CREATE PUBLIC SYNONYM "Успеваемость" FOR C##PDW_CORE."Успеваемость";
CREATE PUBLIC SYNONYM "Нагрузка_преподавателя" FOR C##PDW_CORE."Нагрузка_преподавателя";
CREATE PUBLIC SYNONYM "Группы" FOR C##PDW_CORE."Группы";


CREATE PUBLIC SYNONYM ADD_DISCIPLINE FOR C##PDW_CORE.ADD_DISCIPLINE;
CREATE PUBLIC SYNONYM ADD_FACULTY FOR C##PDW_CORE.ADD_FACULTY;
CREATE PUBLIC SYNONYM ADD_GROUP FOR C##PDW_CORE.ADD_GROUP;
CREATE PUBLIC SYNONYM ADD_LAB FOR C##PDW_CORE.ADD_LAB;
CREATE PUBLIC SYNONYM ADD_SPECIALITIS FOR C##PDW_CORE.ADD_SPECIALITIS;
CREATE PUBLIC SYNONYM ADD_STUDENT FOR C##PDW_CORE.ADD_STUDENT;
CREATE PUBLIC SYNONYM ADD_SUBGROUP FOR C##PDW_CORE.ADD_SUBGROUP;
CREATE PUBLIC SYNONYM ADD_TEACHER FOR C##PDW_CORE.ADD_TEACHER;
CREATE PUBLIC SYNONYM ADD_WORK FOR C##PDW_CORE.ADD_WORK;
CREATE PUBLIC SYNONYM REMOVE_DISCIPLINE FOR C##PDW_CORE.REMOVE_DISCIPLINE;
CREATE PUBLIC SYNONYM REMOVE_FACULTY FOR C##PDW_CORE.REMOVE_FACULTY;
CREATE PUBLIC SYNONYM REMOVE_GROUP FOR C##PDW_CORE.REMOVE_GROUP;
CREATE PUBLIC SYNONYM REMOVE_LAB FOR C##PDW_CORE.REMOVE_LAB;
CREATE PUBLIC SYNONYM REMOVE_SPECIALITIS FOR C##PDW_CORE.REMOVE_SPECIALITIS;
CREATE PUBLIC SYNONYM REMOVE_STUDENT FOR C##PDW_CORE.REMOVE_STUDENT;
CREATE PUBLIC SYNONYM REMOVE_TEACHER FOR C##PDW_CORE.REMOVE_TEACHER;
CREATE PUBLIC SYNONYM REMOVE_WORK FOR C##PDW_CORE.REMOVE_WORK;
CREATE PUBLIC SYNONYM SET_PROGRESS FOR C##PDW_CORE.SET_PROGRESS;
CREATE PUBLIC SYNONYM GET_KOORS_BY_YEAR FOR C##PDW_CORE.GET_KOORS_BY_YEAR;

CREATE PUBLIC SYNONYM TEACHER_DISCIPLINE_LIST FOR C##PDW_CORE.TEACHER_DISCIPLINE_LIST;
CREATE PUBLIC SYNONYM STUDENT_LIST FOR C##PDW_CORE.STUDENT_LIST;
CREATE PUBLIC SYNONYM LAB_LIST FOR C##PDW_CORE.LAB_LIST;
CREATE PUBLIC SYNONYM KOORS_LIST FOR C##PDW_CORE.KOORS_LIST;
CREATE PUBLIC SYNONYM FACULTY_LIST FOR C##PDW_CORE.FACULTY_LIST;
