drop sequence "Факультет_SEQ";
drop sequence "Дисциплина_SEQ";
drop sequence "Преподаватель_SEQ";
drop sequence "Лабораторные_SEQ";
drop sequence "Студенты_SEQ";
drop sequence "Подгруппы_SEQ";
drop sequence "Группы_SEQ";
drop sequence "Нагрузка_преподавателя_SEQ";
drop sequence "Успеваемость_SEQ";